language: dart

dart:
  - 2.3.0
  - stable

dart_task:
  - test: -P travis

matrix:
  include:
    # Only validate formatting using the stable release
    - dart: stable
      dart_task: dartfmt
    - dart: stable
      dart_task:
        dartanalyzer: --fatal-infos --fatal-warnings .
    - dart: 2.3.0
      dart_task:
        dartanalyzer: --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
