include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
linter:
  rules:
    - avoid_null_checks_in_equality_operators
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_fields
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_brace_in_string_interps
